theme: jekyll-theme-architect

title: Yuri Andrei Gelsleichter
description: Personal page

#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: Your Google Analytics tracking ID
